---
services:
  httpd:
    build:
      context: ./httpd
    ports:
      - 127.0.0.1:${HTTPD_HOST_PORT}:80
      - 127.0.0.1:${HTTPD_HOST_SSL_PORT}:443
    volumes:
      - ./DocumentRoot:/var/www/html:z
      - phpmyadmin_data:/var/www/phpmyadmin:ro
    depends_on:
      - php

  database:
    image: docker.io/mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 127.0.0.1:${MYSQL_HOST_PORT}:3306
    volumes:
      - dbdata:/var/lib/mysql

  database-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - database
    volumes:
      - ./db-backup:/backup:z
    environment:
      MYSQL_HOST: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MAX_BACKUPS: ${MYSQL_CRON_BACKUP_MAX_BACKUPS}
      EXIT_BACKUP: ${MYSQL_CRON_BACKUP_EXIT_BACKUP}
      GZIP_LEVEL: ${MYSQL_CRON_BACKUP_GZIP_LEVEL}
      CRON_TIME: ${MYSQL_CRON_BACKUP_CRON_TIME}
      MYSQLDUMP_OPTS: ${MYSQL_CRON_BACKUP_MYSQDUMP_OPTS}
    restart: unless-stopped

  php:
    build:
      context: ./php
      target: post
      args:
        PHP_VERSION: ${PHP_FPM_VERSION}-fpm
    user: ${PHP_FPM_RUNTIME_UID}
    environment:
      PHP_FPM_MAX_EXECUTION_TIME: ${PHP_FPM_MAX_EXECUTION_TIME}
      PHP_FPM_MEMORY_LIMIT: ${PHP_FPM_MEMORY_LIMIT}
      PHP_FPM_POST_MAX_SIZE: ${PHP_FPM_POST_MAX_SIZE}
      PHP_FPM_UPLOAD_LIMIT: ${PHP_FPM_UPLOAD_LIMIT}
      PHP_FPM_ERROR_REPORTING: ${PHP_FPM_ERROR_REPORTING}
      PHP_FPM_DISPLAY_ERRORS: ${PHP_FPM_DISPLAY_ERRORS}
    volumes:
      - ./DocumentRoot:/var/www/html:z

  phpmyadmin:
    image: docker.io/phpmyadmin:fpm
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MAX_EXECUTION_TIME: ${PHP_FPM_MAX_EXECUTION_TIME}
      MEMORY_LIMIT: ${PHP_FPM_MEMORY_LIMIT}
      UPLOAD_LIMIT: ${PHP_FPM_UPLOAD_LIMIT}
    volumes:
      - phpmyadmin_data:/var/www/html:ro
    depends_on:
      - database

volumes:
  dbdata:
  phpmyadmin_data:
